import { useState, useEffect } from "react";
import UploadForm from "./UploadForm";
import RadarChart from "./RadarChart";
import "../../App.css";
import Mockup from "./Mockup";
import { Box, Typography, Divider, Stack, Paper } from "@mui/material";

function MVP() {
  const [jobId, setJobId] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [clearValues, setClearValues] = useState(null);
  const [isMock, setIsMock] = useState(false);

  useEffect(() => {
    const forceMock = false; // <-- toggle this flag for testing
    const isGitHubPages =
      window.location.hostname.includes("github.io") || forceMock;
    setIsMock(isGitHubPages);

    if (isGitHubPages) {
      setClearValues({
        C: 0.8,
        L: 0.9,
        E: 0.7,
        A: 0.6,
        R: 0.8,
      });
    }
  }, []);

  return (
    <>
      {isMock ? (
        <>
          <Mockup />
          <Divider
            sx={{
              my: 4,
              mx: "auto",
              borderColor: "#ccc",
            }}
          />
          <Typography
            variant="h4"
            sx={{
              textAlign: "center",
              mt: 2,
              mb: 1,
              fontWeight: "bold",
            }}
          >
            Team Communication Evaluation
          </Typography>
          <Box
            component={Paper}
            elevation={3}
            sx={{
              borderRadius: 2,
              p: { xs: 2, md: 4 },
              mt: 4,
              maxWidth: "900px",
              mx: "auto",
              backgroundColor: "#f9f9f9",
            }}
          >
            <Typography variant="body1">
              This is a thesis project to explore how AI is able to evaluate
              team communication in a team meeting. <br />
              With the meeting audio, AI is used to evaluate how effective the
              team's communication is, with respect to each aspect of the CLEAR
              model. The score on each aspect of CLEAR is reflected in the Radar
              chart while a summary of insight and recommendations are generated
              based on the evaluation criteria.
            </Typography>
          </Box>
          <Box
            component={Paper}
            elevation={3}
            sx={{
              borderRadius: 2,
              p: { xs: 2, md: 4 },
              mt: 4,
              maxWidth: "900px",
              mx: "auto",
              backgroundColor: "#f9f9f9",
            }}
          >
            <Typography variant="h5" gutterBottom>
              CLEAR Model Radar Chart
            </Typography>
            <Typography variant="subtitle1" gutterBottom>
              Each aspect of CLEAR Model is given a score between 0 and 1
              <Stack
                component="ul"
                sx={{
                  width: "fit-content",
                  margin: "0 auto",
                  paddingLeft: 0,
                  listStylePosition: "outside",
                  textAlign: "left",
                }}
              >
                <li>
                  <strong>C</strong> - Curious, caring and open-minded
                </li>
                <li>
                  <strong>L</strong> - Listen to one another
                </li>
                <li>
                  <strong>E</strong> - Encourage everyone to contribute
                </li>
                <li>
                  <strong>A</strong> - Avoid dominating or interrupting
                </li>
                <li>
                  <strong>R</strong> - Repeat and review people’s points
                </li>
              </Stack>
            </Typography>

            <RadarChart
              values={{
                C: 0.8,
                L: 0.7,
                E: 0.7,
                A: 0.6,
                R: 0.8,
              }}
            />
            <Box sx={{ mt: 3 }}>
              <Typography variant="subtitle2" gutterBottom>
                <strong>SCORES:</strong>
              </Typography>
              <strong>C</strong> - 0.8 | <strong>L</strong> - 0.7 |{" "}
              <strong>E</strong> - 0.7 | <strong>A</strong> - 0.6 |{" "}
              <strong>R</strong> - 0.8
            </Box>
          </Box>
          <Box
            component={Paper}
            elevation={3}
            sx={{
              borderRadius: 2,
              p: { xs: 2, md: 4 },
              mt: 4,
              maxWidth: "900px",
              mx: "auto",
              backgroundColor: "#f9f9f9",
            }}
          >
            <Typography variant="h5" gutterBottom>
              Effective Team Communication Areas
              <Typography variant="subtitle1" gutterBottom>
                The insights are generated by AI, based on the CLEAR Model
                criteria.
              </Typography>
            </Typography>
          </Box>
          <Box
            component={Paper}
            elevation={3}
            sx={{
              borderRadius: 2,
              p: { xs: 2, md: 4 },
              mt: 4,
              maxWidth: "900px",
              mx: "auto",
              backgroundColor: "#f9f9f9",
            }}
          >
            <Typography variant="h5" gutterBottom>
              Recommendations for Team
              <Typography variant="subtitle1" gutterBottom>
                The recommendations are generated by AI, based on the CLEAR Model
                criteria.
              </Typography>
            </Typography>
          </Box>
        </>
      ) : (
        <>
          <UploadForm
            setUploading={setUploading}
            onUploadComplete={(id) => setJobId(id)}
            onClearValuesReady={(values) => setClearValues(values)}
          />
          {uploading && <p>Uploading video... please wait ⏳</p>}
          {clearValues && <RadarChart values={clearValues} />}
        </>
      )}
    </>
  );
}

export default MVP;
