import { useState, useEffect } from "react";
import UploadForm from "./UploadForm";
import RadarChart from "./RadarChart";
import "../../App.css";
import Mockup from "./Mockup";
import { Box, Typography, Divider, Stack, Paper } from "@mui/material";

function MVP() {
  const [jobId, setJobId] = useState(null);
  const [uploading, setUploading] = useState(false);
  const [clearValues, setClearValues] = useState(null);
  const [isMock, setIsMock] = useState(false);

  useEffect(() => {
    const forceMock = false; // <-- toggle this flag for testing
    const isGitHubPages =
      window.location.hostname.includes("github.io") || forceMock;
    setIsMock(isGitHubPages);

    if (isGitHubPages) {
      setClearValues({
        C: 0.8,
        L: 0.9,
        E: 0.7,
        A: 0.6,
        R: 0.8,
      });
    }
  }, []);

  return (
    <>
      {isMock ? (
        <>
          <Mockup />
          <Divider
            sx={{
              my: 4,
              mx: "auto",
              borderColor: "#ccc",
            }}
          />
          <Typography
            variant="h4"
            sx={{
              textAlign: "center",
              mt: 2,
              mb: 1,
              fontWeight: "bold",
            }}
          >
            Team Communication Evaluation
          </Typography>
          <Box
            component={Paper}
            elevation={3}
            sx={{
              borderRadius: 2,
              p: { xs: 2, md: 4 },
              mt: 4,
              maxWidth: "900px",
              mx: "auto",
              backgroundColor: "#f9f9f9",
            }}
          >
            <Typography variant="h5" gutterBottom>
              CLEAR Model Radar Chart
            </Typography>
            <Typography variant="subtitle1" gutterBottom>
              Each aspect of CLEAR Model is given a score between 0 and 1
              <Stack component="ul">
                <li>C - Curious, caring and open-minded</li>
                <li>L - Listen to one another</li>
                <li>E - Encourage everyone to contribute</li>
                <li>A - Avoid dominating or interrupting</li>
                <li>R - Repeat and review people’s points</li>
              </Stack>
            </Typography>

            <RadarChart
              values={{
                C: 0.8,
                L: 0.9,
                E: 0.7,
                A: 0.6,
                R: 0.8,
              }}
            />
          </Box>

          <Box
            component={Paper}
            elevation={3}
            sx={{
              borderRadius: 2,
              p: { xs: 2, md: 4 },
              mt: 4,
              maxWidth: "900px",
              mx: "auto",
              backgroundColor: "#f9f9f9",
            }}
          >
            <Typography variant="h5" gutterBottom>
              Recommendations on Team Communication
              <Typography variant="subtitle1" gutterBottom>
                The recommendations are generated by AI, based on the CLEAR
                Model criteria.
              </Typography>
            </Typography>
          </Box>
        </>
      ) : (
        <>
          <UploadForm
            setUploading={setUploading}
            onUploadComplete={(id) => setJobId(id)}
            onClearValuesReady={(values) => setClearValues(values)}
          />
          {uploading && <p>Uploading video... please wait ⏳</p>}
          {clearValues && <RadarChart values={clearValues} />}
        </>
      )}
    </>
  );
}


export default MVP;
